version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: api_flask_python_hello-world_basic-rbac
    container_name: api_flask_python_hello-world_basic-rbac
    ports:
      - 6060:6060
