FROM python:3

WORKDIR /home/app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY .env .
COPY . .

EXPOSE 6060

RUN useradd -M auth0
USER auth0

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
